#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/myemployees
#    username: root
#    password: cpy398129519
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8888


spring:
  datasource:
    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.git,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000    #          慢查询时间
          enabled: true

        wall:
          enabled: true
#          config:
#            update-allow: true



